_format_version: "1.1"
services:
  - host: reqres.in
    name: example-redis
    port: 443
    protocol: https
    routes:
      - name: route-redis
        paths:
          - /redis
        strip_path: true

    plugins:
    - name: sonic-boom
      config:
        response_code:
          - 200
          - 301
          - 404
        request_method:
          - GET
          - HEAD
          - POST
          - PUT
        content_type:
          - "text/plain"
          - "text/html; charset=utf-8"
          - "application/json"
          - "application/json; charset=utf-8"
        vary_headers:
          - Authorization
        cache_ttl: 15
        cacheable_body_max_size: 1000000
        strategy: redis
        redis:
          host: redis
          pool-size: 10
          max-retries: 5
          db-number: 1
          dial-timeout: 0
          read-timeout: 0
          write-timeout: 0
          pool-timeout: 0
          idle-timeout: 0
        log:
          log_level: info
          diode_enabled: false
          console_logging_enabled: true
          file_log:
            enabled: true
            folder: /var/log
            filename: sonic-boom-redis.log

  - host: reqres.in
    name: example-in-memory
    port: 443
    protocol: https
    routes:
      - name: route-in-memory
        paths:
          - /in-memory
        strip_path: true

    plugins:
    - name: sonic-boom
      config:
        response_code:
          - 200
          - 301
          - 404
        request_method:
          - GET
          - HEAD
          - POST
          - PUT
        content_type:
          - "text/plain"
          - "text/html; charset=utf-8"
          - "application/json"
          - "application/json; charset=utf-8"
        vary_headers:
          - Authorization
        cache_ttl: 15
        cacheable_body_max_size: 1000000
        strategy: in-memory
        in-memory:
          max_cost: 100
          num_counters: 1000
          buffer_items: 64
        log:
          log_level: info
          diode_enabled: false
          console_logging_enabled: true
          file_log:
            enabled: true
            folder: /var/log
            filename: sonic-boom-in-memory.log

  - host: reqres.in
    name: example
    port: 443
    protocol: https
    routes:
      - name: route
        paths:
          - /ex
        strip_path: true

    plugins:
    - name: sonic-boom
      config:
        response_code:
          - 200
          - 301
          - 404
        request_method:
          - GET
          - HEAD
          - POST
          - PUT
        content_type:
          - "text/plain"
          - "text/html; charset=utf-8"
          - "application/json"
          - "application/json; charset=utf-8"
        vary_headers:
          - Authorization
          - Accept-Encoding
          - Accept-Language
        filters:
          - name: path and header
            rules:
            - regexp: ".*page=\\(.*\\).*"
            - header: "Authorization"
              regexp: ".*dXNlcm5hbWU6cGFzc3dvcmQ=.*"
              # `username:password` == dXNlcm5hbWU6cGFzc3dvcmQ=
            cache_ttl: 30
          - name: path
            rules:
              - regexp: ".*page=\\(.*\\).*"
            cache_ttl: 30
          - name: header
            rules:
              - header: "Authorization"
                regexp: ".*dXNlcm5hbWU6cGFzc3dvcmQ=.*"
            cache_ttl: 30
        cache_ttl: 15
        cacheable_body_max_size: 1000000
        strategy: redis
        redis:
          host: redis
        log:
          log_level: debug
          console_logging_enabled: true
          file_log:
            enabled: true
            folder: /var/log/kong
            filename: sonic-boom.log

  - host: reqres.in
    name: proxycache
    port: 443
    protocol: https
    #  - host: mock-api.backend
    #    name: dev
    #    port: 9000
    #    protocol: http
    routes:
      - name: route3
        paths:
          - /proxycache
        strip_path: true

    plugins:
    - name: proxy-cache
      config:
        response_code:
          - 200
          - 301
          - 404
        request_method:
          - GET
          - HEAD
          - POST
          - PUT
        content_type:
          - "text/plain"
          - "text/html; charset=utf-8"
          - "application/json"
          - "application/json; charset=utf-8"
        vary_headers:
          - Authorization
        cache_ttl: 15
        strategy: memory


  - host: reqres.in
    name: no_plugins
    port: 443
    protocol: https
    routes:
      - name: route4
        paths:
          - /noplugins
        strip_path: true
