services:
  redis:
    image: redis
    ports:
      - '6379:6379'

  redis-cluster:
    image: grokzen/redis-cluster:6.2.8
    environment:
      - IP=0.0.0.0
      - INITIAL_PORT=7000
      - MASTERS=3
      - SLAVES_PER_MASTER=0
    ports:
      - '7000:7000'
      - '7001:7001'
      - '7002:7002'
    healthcheck:
      test: ["CMD", "bash", "-c", "redis-cli -p 7000 cluster info | grep -q cluster_state:ok"]
      interval: 5s
      timeout: 3s
      retries: 20

  kong:
    # image: ghcr.io/unchartedsky/sonic-boom:sha-01f9cc1
    # image: kong:3.9.0-ubuntu
    build: .
    environment:
      # Kong Configuration
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/config.yml
      - KONG_PLUGINS=bundled,sonic-boom
      - KONG_PLUGINSERVER_NAMES=sonic-boom
      - KONG_PLUGINSERVER_SONIC_BOOM_START_CMD=/kong/go-plugins/sonic-boom
      - KONG_PLUGINSERVER_SONIC_BOOM_QUERY_CMD=/kong/go-plugins/sonic-boom -dump
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_LOG_LEVEL=debug
      - KONG_NGINX_HTTP_GZIP=on
      - KONG_NGINX_HTTP_GZIP_VARY=on
#      - KONG_NGINX_HTTP_GZIP_TYPES="application/json application/json; utf-8"
      - KONG_NGINX_HTTP_GZIP_PROXIED="any"

      # Pass OpenTelemetry environment variables to nginx
      # See https://discuss.konghq.com/t/set-multiple-env-nginx-directives/7532/3
      - KONG_NGINX_MAIN_ENV=OTEL_SDK_DISABLED;env OTEL_SERVICE_NAME;env OTEL_EXPORTER_OTLP_ENDPOINT;env OTEL_EXPORTER_OTLP_PROTOCOL;env OTEL_TRACES_SAMPLER;env OTEL_TRACES_SAMPLER_ARG;env OTEL_PROPAGATORS;env OTEL_RESOURCE_ATTRIBUTES;env OTEL_LOG_LEVEL

      # OpenTelemetry Configuration
      - OTEL_SDK_DISABLED=true
      - OTEL_SERVICE_NAME=sonic-boom
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_TRACES_SAMPLER=parentbased_always_on
      - OTEL_TRACES_SAMPLER_ARG=1.0
      - OTEL_PROPAGATORS=b3
      - OTEL_RESOURCE_ATTRIBUTES=service.name=sonic-boom
      - OTEL_LOG_LEVEL=info
    ports:
      - '8000:8000'
    restart: on-failure
    volumes:
      - ./config_v1.yml:/kong/config.yml
      - ./bin/linux-arm64:/kong/go-plugins

volumes:
  shared-volume:
